### ISSUE TITLE
(Train Model + CTC Office) NullPointerException at Red Line (possible call to previous block)

### ISSUE THREAD

**Issue by Riteshlogin** [xaviertorgerson/North-Shore-Extension#21]
I am attempting to send two trains to block 21 on the red line (coming directly from the yard). One train got to block 17 and then stopped, but there were no errors after that. It simply stopped at 17. I then sent a second train to block 21, and it stopped at block 1 and then created this error- 

---------------------------------- The stuff before this point was normal.---------------------------------- The first things that are printed are the last printouts from the first train going to block 17. 

train mobing right
train mobing right
Third speed auth seton lineRedand block num16 with authority 1375.0
The new authority for block 16 suggested by CTC is 0.8525
New authority for block 16 determined by Wayside is 0.8525
Set NEW Authority of 0.8525 on block num 16
train mobing right
train mobing right
Third speed auth seton lineRedand block num17 with authority 1175.0
The new authority for block 17 suggested by CTC is 0.7285
New authority for block 17 determined by Wayside is 0.7285
Set NEW Authority of 0.7285 on block num 17
Red suggestion
The new authority for block 77 suggested by CTC is 0.62
New authority for block 77 determined by Wayside is 0.62
Set NEW Authority of 0.62 on block num 77
Third speed auth seton lineRedand block num77 with authority 1950.0 (This is in meters, not miles)
The new authority for block 77 suggested by CTC is 1.209
New authority for block 77 determined by Wayside is 1.209
Set NEW Authority of 1.209 on block num 77
Third speed auth seton lineRedand block num9 with authority 1875.0
The new authority for block 9 suggested by CTC is 1.1625
New authority for block 9 determined by Wayside is 1.1625
Set NEW Authority of 1.1625 on block num 9
Third speed auth seton lineRedand block num8 with authority 1800.0
The new authority for block 8 suggested by CTC is 1.116
New authority for block 8 determined by Wayside is 1.116
Set NEW Authority of 1.116 on block num 8
Third speed auth seton lineRedand block num7 with authority 1725.0
The new authority for block 7 suggested by CTC is 1.0695
New authority for block 7 determined by Wayside is 1.0695
Set NEW Authority of 1.0695 on block num 7
Third speed auth seton lineRedand block num6 with authority 1675.0
The new authority for block 6 suggested by CTC is 1.0385
New authority for block 6 determined by Wayside is 1.0385
Set NEW Authority of 1.0385 on block num 6
Third speed auth seton lineRedand block num5 with authority 1625.0
The new authority for block 5 suggested by CTC is 1.0075
New authority for block 5 determined by Wayside is 1.0075
Set NEW Authority of 1.0075 on block num 5
Third speed auth seton lineRedand block num4 with authority 1575.0
The new authority for block 4 suggested by CTC is 0.97650003
New authority for block 4 determined by Wayside is 0.97650003
Set NEW Authority of 0.97650003 on block num 4
Third speed auth seton lineRedand block num3 with authority 1525.0
The new authority for block 3 suggested by CTC is 0.9455
New authority for block 3 determined by Wayside is 0.9455
Set NEW Authority of 0.9455 on block num 3
Third speed auth seton lineRedand block num2 with authority 1475.0
The new authority for block 2 suggested by CTC is 0.9145
New authority for block 2 determined by Wayside is 0.9145
Set NEW Authority of 0.9145 on block num 2
Third speed auth seton lineRedand block num1 with authority 1425.0
The new authority for block 1 suggested by CTC is 0.8835
New authority for block 1 determined by Wayside is 0.8835
Set NEW Authority of 0.8835 on block num 1
**Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at TrackModel.update(TrackModel.java:115)
        at NSE$1.actionPerformed(NSE.java:35)**

**Comment by Riteshlogin** [comment]
I had an additional null pointer exception when I moved the train around the bottom left loop on the green line. It did manage to escape the infinite loop, but then once it got to the beginning of N I set the switch to make the train go up R, but then it hit a null pointer exception at line 115 yet again.
